Tilføjede Fit er Fit (wip)
f-klubben/sangbog pull request #16
Opened 2022-06-03 12:22 UTC by ScumbagDog

Lavede lidt latex til "Fit er Frit"-sangen, tilsendt fra en af fitnisserne.

Ikke endelig version, kan godt være der er lidt, der skal pudses af inden den merges ind.

2024-01-04 15:15 UTC, JakobTopholt requested changes
Lgtm, with the exception that I am of the opinion that the last verse could be omitted.

We'll take this up the next F-choir meeting in March.

2024-04-16 07:30 UTC, krestenlaust commented
> Lgtm, with the exception that I am of the opinion that the last verse could be omitted.
> 
> We'll take this up the next F-choir meeting in March.

You didn't take it up

2024-04-16 07:31 UTC, krestenlaust commented
I agree that the last verse isn't 'tidssvarende', but it's a part of the original song. Maybe we could leave it in, but in italics or maybe in brackets

2024-05-01 14:14 UTC, JakobTopholt commented
Kresten is spitting facts, it was not taken up. I'll perhaps look at this later.

2024-06-14 19:42 UTC, VirtualSatai commented on main.tex
> +=======
Er dette intentionelt eller noget merge conflict som er forblivet ?

2024-06-14 21:24 UTC, mads256h commented on main.tex
> +=======
No way det er intentionelt

2024-06-16 10:27 UTC, JakobTopholt requested changes
Removing the one line it's lgtm.

Also, I removed the last verse some time ago as i didn't like it, feels a bit dictatorial but feel free to send me some feedback on it in the future.

2024-06-16 10:27 UTC, JakobTopholt commented on main.tex
> +=======
```suggestion
\input{sange/fiterfrit.tex}
```

2024-06-16 10:32 UTC, JakobTopholt approved these changes

2024-06-16 10:32 UTC, merged