Update Makefile
f-klubben/sangbog pull request #47
Opened 2024-08-25 10:23 UTC by JakobTopholt

Added Sebastian's suggestion from https://github.com/f-klubben/sangbog/issues/45 and it works

2024-08-25 10:25 UTC, JakobTopholt commented
Det virkede på min virtual machine 😭

2024-08-25 10:27 UTC, Mast3rwaf1z commented
opdater lige actions, så skal jeg nok kigge på det

2024-12-22 21:09 UTC, krestenlaust requested changes

2024-12-22 21:09 UTC, krestenlaust commented on sange/alleDAT'erErGladeForPorter.tex
Hvad laver #49 herinde?

2025-03-20 18:25 UTC, closed without merging