Tilføjede På Cassiopeia til FooBar
f-klubben/sangbog pull request #5
Opened 2021-10-04 14:09 UTC by ScumbagDog

Jeg har lavet en ny sang, pls review

2021-10-04 15:19 UTC, hrjakobsen approved these changes
LGTM! Det her er hvad målet med Hacktoberfest skal være. 

Måske lidt modigt at have "å" i filnavnet btw.

2021-10-04 15:55 UTC, ScumbagDog commented
Jeg har brug for spænding i mit liv

2021-10-04 15:56 UTC, falkecarlsen approved these changes
Jeg savner et mp3 preview af sangen, tjek gerne at den stadig compiler med 'å' som filnavn

2021-10-04 16:04 UTC, ScumbagDog commented
Den kaster i hvert fald ingen fejl ¯\\_ (ツ)_/¯
![image](https://user-images.githubusercontent.com/33865465/135885044-fb82bc08-c7c3-458d-b770-380675d07401.png)

Og hvis du ikke passer på, kommer der en cover-version med ukulele og kazoo uden foran din hoveddør kl. 3 om natten efter en Nork-bar @falkecarlsen

2021-10-04 16:06 UTC, ScumbagDog commented
![image](https://user-images.githubusercontent.com/33865465/135885436-61519315-3e47-4c1c-99d3-2abfa63b4ebc.png)
Nu med linjen hvor den bliver indlæst

2021-10-04 16:50 UTC, falkecarlsen requested changes
Nice, compile og commit gerne den nye `main_book.pdf`, så folk ikke behøves et LaTeX system for at kunne se den nyeste sangbog

2021-10-04 16:56 UTC, ScumbagDog commented
Vil næsten hellere have det som en form for CI, så vi ikke prøver at merge PDF'er der er forskellige.
Jeg kan godt smide den op på Fikien, hvis det bare er for at have en opdateret sangbog.

2021-10-06 14:44 UTC, falkecarlsen approved these changes

2021-11-22 15:43 UTC, ScumbagDog commented
Ændrede \today til \the\year{} for at beholde årsformatet fra forrige sangbøger (altså kun at skrive år, frem for den fulde dato)

2021-11-27 00:56 UTC, merged