Added gitignore
f-klubben/sangbog pull request #6
Opened 2021-10-04 14:14 UTC by ScumbagDog

Tilføjede gitignore så vi ikke pusher en masse byggede bøger til git

2021-10-04 22:51 UTC, hrjakobsen requested changes
You should add `main.ind` to `.gitignore`. This is the index file generated by `makeindex main` from #1 and #8.

2021-10-04 23:43 UTC, ScumbagDog commented
You got it, Chief

2021-10-05 01:09 UTC, hrjakobsen approved these changes

2021-10-05 01:13 UTC, hrjakobsen commented
Dette PR bør merges umidelbart før #1 og #8 for at sikre os at der altid er en kompilet version tilgængelig (jvf. #5).

2021-10-05 11:15 UTC, merged