CI: Add automatic compilation of booklet
f-klubben/sangbog pull request #8
Opened 2021-10-04 19:55 UTC by hrjakobsen

Som opfølging på diskussionerne i #3 og #5 har jeg tilføjet en Github action som compiler sangbogen ved PRs og uploader en compilet version til hvert commit. Når man tagger et release tilføjer den også den compilede version dertil. Se https://github.com/hrjakobsen/sangbog/releases for et eksempel.

2021-10-04 21:57 UTC, VirtualSatai commented
LGTM. Lækkert med kompileret PDF med i release. Når der merges så lav gerne link på FIKI'en til: `https://github.com/f-klubben/sangbog/releases/latest/download/sangbog.pdf` Så er der er permanent link til den nyeste udgave.

2021-10-04 22:00 UTC, VirtualSatai requested changes

2021-10-04 22:00 UTC, VirtualSatai commented on .github/workflows/compile.yml
> +          latex main.tex
Jeg tror du mangler noget således der bliver lavet et index/indholdsfortegnelse ala. https://github.com/f-klubben/sangbog/blob/main/Makefile#L15 

Den findes ikke i den PDF på dit repo: https://github.com/hrjakobsen/sangbog/releases/download/2021-10-04.3/sangbog.pdf

2021-10-04 22:37 UTC, hrjakobsen commented on .github/workflows/compile.yml
> +          latex main.tex
Det har du da ret i. Jeg havde godt tidligere set diskussionen i #1, men havde ikke lagt mærke til at det samme var gældende her. Nyeste fil https://github.com/hrjakobsen/sangbog/releases/download/2021-10-04.4/sangbog.pdf indeholder indholdsfortegnelsen.

2021-10-05 07:05 UTC, VirtualSatai approved these changes
LGTM

2021-10-05 07:54 UTC, falkecarlsen approved these changes
Very nice :shipit:

2021-10-05 11:16 UTC, merged